#################
### AUTOSTART ###
#################

exec =sleep 1 && /home/$USER/.config/hypr/scripts/rndWlpr.sh &
exec-once = [workspace 3 silent] $browser
exec-once = [workspace 2 silent] $terminal -e $EDITOR
exec-once = [workspace 1 silent] $terminal 
exec-once = sleep 1 && waybar

