###############
### IMPORTS ###
###############

# My program variables
source = ~/.config/hypr/defaultProgs.conf
# Keyboard and mouse
source = ~/.config/hypr/keyboardMouse.conf
# Keybinds
source = ~/.config/hypr/binds.conf
# Look and feel
source = ~/.config/hypr/theme.conf
# Permissions
source = ~/.config/hypr/perms.conf
# Autostart
source = ~/.config/hypr/autostart.conf


################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=,preferred,auto,1.2


#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hyprland.org/Configuring/Environment-variables/

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24


ecosystem {
    no_donation_nag = true
    enforce_permissions = true
}

binds {
    workspace_center_on = 1
    hide_special_on_workspace_change = true
}


##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

xwayland {
    force_zero_scaling = true
}
